to_do_liste/to_do_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'to_do_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:liste_title>/', views.detail, name='detail'),
    path('<str:liste_title>/new_detail/', views.new_detail, name='new_detail'),
    path('/new_list/', views.new_list, name='new_list'),
]

to_do_liste/to_do_liste/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('to_do_app/', include('to_do_app.urls'))
]

to_do_liste/to_do_app/models.py
from django.db import models
import datetime

class Liste(models.Model):
    liste_title = models.CharField('name of list', max_length = 50)
    liste_text = models.TextField('text of list', max_length = 1000)
    pub_date = models.DateTimeField('date of list')
    liste_status = models.IntegerField(choices=[[1,'Todo'], [2, 'Done'], [3, 'Canceled']])
    
    def __str__(self):
      return self.liste_title


# Create your models here.

to_do_liste/to_do_app/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Liste 
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

def index(request):
    latest_listen = Liste.objects.order_by('pub_date')
    to_do_listen = Liste.objects.filter(liste_status=1)
    done_listen = Liste.objects.filter(liste_status=2)
    canceled_listen = Liste.objects.filter(liste_status=3)
    context = {'latest_listen':latest_listen, 'to_do_listen':to_do_listen, 'done_listen':done_listen, 'canceled_listen':canceled_listen}
    return render(request, 'to_do_app/index.html', context)


def detail(request, liste_title):
    liste =  Liste.objects.get(liste_title=liste_title)
    return render(request, 'to_do_app/detail.html', {'liste':liste})


def new_detail(request, liste_title):
    liste =  Liste.objects.get(liste_title=liste_title)
    liste.liste_status = request.POST.get("choice")
    liste.save(update_fields=["liste_status"])
    return HttpResponseRedirect(reverse('to_do_app:detail', args=(liste.liste_title,)))


def new_list(request):
    print(request.POST)
    new_liste = Liste()
    new_liste.liste_title = request.POST.get("title")
    new_liste.liste_text = request.POST.get("text")
    new_liste.pub_date = timezone.now()
    new_liste.liste_status = request.POST.get("choice")
    new_liste.save()
    return HttpResponseRedirect(reverse('to_do_app:index'))

to_do_liste/to_do_app/templates/to_do_app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Liste {{liste.liste_title}}</title>
</head>
<body>
    <div class="card text-center m-5" style="width: 18rem;">
        <div class="card-header">
            {{liste.liste_title}}
        </div>
        <div class="card-body">
          <h5 class="card-title">Status: {{ liste.get_liste_status_display }}</h5>
          <p class="card-text">{{ liste.liste_text }}
            <form action="{% url 'to_do_app:new_detail' liste.liste_title %}" method="post" id="choice">
                <div class="form-group">
                    {% csrf_token %}
                    <select id="choice" name="choice" form="choice">
                        <option value="1">Todo</option>
                        <option value="2">Done</option>
                        <option value="3">Canceled</option>
                    </select>
                </div>    
          </p>
            <button type="submit" class="btn btn-primary" value="Change the status">Change the status</button></form>
            <a href="{% url 'to_do_app:index' %}" class="card-link">Zurück</a>
        </div>
        <div class="card-footer text-muted">
            {{liste.pub_date}}
        </div>
      </div>
</body>
</html>

to_do_liste/to_do_app/templates/to_do_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>To Do - Listen</title>
</head>
<body>
    <div class="container justify-content-center">
        <div class="row justify-content-center mt-md-3">
            <div class="col-12 col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h3>Neue Liste anlegen</h3>
                        <form action="{% url 'to_do_app:new_list' %}" method="post">
                            <div class="form-group">
                                {% csrf_token %}
                                <label for="title">Name of Liste:</label><br>
                                <input type="text" class="form-control" id="title" name="title"><br>
                            </div>
                            <div class="form-group">
                                <label for="text">Text of Liste:</label><br>
                                <textarea id="text" class="form-control" name="text"></textarea><br> 
                            </div>    
                            <div class="form-group">      
                                <select class="form-control" id="choice" name="choice">
                                <option value="1">Todo</option>
                                <option value="2">Done</option>
                                <option value="3">Canceled</option>
                                </select>
                            </div> 
                            <button type="submit" class="btn btn-primary" value="new_list">Anlegen</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4 mt-5 ml-5">
                <h3>All Listen</h3>
                <hr>
                {% if latest_listen %}
                <ol>
                {% for list in latest_listen %}
                <li><a href="{% url 'to_do_app:detail' list.liste_title %}">{{ list.liste_title }}</a></li>
                {% endfor %}
                </ol>
                {% else %}
                <p> No Listen </p>
                {% endif %}
            </div>
        </div>
        <hr>
        <div class="row row-cols-md-3 mt-md-5">
            <div class="col-12">  
                <div class="d-flex justify-content-right">           
                    <div class="spinner-grow text-danger spinner-border-sm" role="status">
                        <span class="sr-only"></span>
                    </div>
                    <h3 class="ml-3">To Do Listen</h3>
                </div><hr>
                {% if to_do_listen %}
                <ol>
                {% for a in to_do_listen %}
                <li><a href="{% url 'to_do_app:detail' a.liste_title %}">{{ a.liste_title }}</a></li>
                {% endfor %}
                </ol>
                {% else %}
                <p> No Listen </p>
                {% endif %}
            </div>
            <div class="col-12">
                <div class="d-flex justify-content-right">           
                    <div class="spinner-grow text-success spinner-border-sm" role="status">
                        <span class="sr-only"></span>
                    </div>
                    <h3 class="ml-3">Done Listen</h3>
                </div><hr>
                {% if done_listen %}
                <ol>
                {% for a in done_listen %}
                <li><a href="{% url 'to_do_app:detail' a.liste_title %}">{{ a.liste_title }}</a></li>
                {% endfor %}
                </ol>
                {% else %}
                <p> No Listen </p>
                {% endif %}
            </div>
            <div class="col-12">
                <div class="d-flex justify-content-right">           
                    <div class="spinner-grow text-dark spinner-border-sm" role="status">
                        <span class="sr-only"></span>
                    </div>
                    <h3 class="ml-3">Canceled Listen</h3>
                </div><hr>
                {% if canceled_listen %}
                <ol>
                {% for a in canceled_listen %}
                <li><a href="{% url 'to_do_app:detail' a.liste_title %}">{{ a.liste_title }}</a></li>
                {% endfor %}
                </ol>
                {% else %}
                <p> No Listen </p>
                {% endif %}
                <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
            </div>
        </div> 
    </div>
</body>
</html>